### ISSUE TITLE
爬取内容的处理

### ISSUE THREAD

**Issue by Ruffianjiang** [vector4wang/vw-crawler#1]
爬取的内容有没有经过渲染器，因为用python做爬取的时候，是有模拟浏览器渲染的库的，直接爬取和渲染后的结果可能是不一样的

**Comment by vector4wang** [comment]
爬取的内容是否已经被完全渲染还是要看使用的哪种爬虫“工具”，此项目默认使用的是jsoup，也就只能处理一般的网站，如果有有的网站需要经过很复杂的渲染，可能此项目的下载器就失效了，但是可以使用htmlunit代替，遇到更复杂(防爬)的可以使用selenium等等~

**Comment by vector4wang** [comment]
另外如果 @Ruffianjiang 你有一些好的想法，可以交流一下，一起改进此项目
